version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "master"
    ignore:
      - dependency-name: "criterion"
        versions: [">= 0.6"]
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "release-1.29"
    ignore:
      - dependency-name: "criterion"
        versions: [">= 0.6"]
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "release-1.28"
    ignore:
      - dependency-name: "criterion"
        versions: [">= 0.6"]
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "release-1.27"
    ignore:
      - dependency-name: "criterion"
        versions: [">= 0.6"]
    groups:
      all-dependencies:
        patterns:
          - "*"
