version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "master"
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "criterion"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "release-1.29"
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "criterion"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "release-1.28"
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "criterion"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    target-branch: "release-1.27"
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "criterion"
