# Source: ztunnel/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ztunnel-windows
  namespace: istio-system
  labels:
    app.kubernetes.io/name: ztunnel-windows
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "ztunnel"
    app.kubernetes.io/part-of: "istio"
    app.kubernetes.io/version: "1.0.0"
    helm.sh/chart: ztunnel-windows-1.0.0
  annotations:
spec:
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ztunnel-windows
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        istio.io/dataplane-mode: none
        app: ztunnel-windows
        app.kubernetes.io/name: ztunnel-windows
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "ztunnel-windows"
        app.kubernetes.io/part-of: "istio"
        app.kubernetes.io/version: "1.0.0"
        helm.sh/chart: ztunnel-windows-1.0.0
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      serviceAccountName: ztunnel
      hostNetwork: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
      - name: istio-proxy
        image: "istiolocaltesting.azurecr.io/ztunnel-windows:20250322-9"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\SYSTEM"
        readinessProbe:
          httpGet:
            port: 15021
            path: /healthz/ready
        args:
        - proxy
        - ztunnel
        env:
        - name: ALT_XDS_HOSTNAME
          value: "istiod-1-25-0.istio-system.svc"
        - name: ALT_CA_HOSTNAME
          value: "istiod-1-25-0.istio-system.svc"
        - name: USE_ENV_FOR_DEFAULT_ISTIOD_ADDR
          value: "true"
        - name: REVISION
          value: "1-25-0"
        - name: RUST_LOG
          value: "trace"
        - name: RUST_BACKTRACE
          value: "1"
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: INPOD_ENABLED
          value: "true"
        - name: INPOD_UDS
          value: \\.\pipe\istio-zds
        - name: INPOD_PORT_REUSE
          value: "false"
        - name: TERMINATION_GRACE_PERIOD_SECONDS
          value: "30"
        - name: IPV6_ENABLED
          value: "false"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /var/run/ztunnel
          name: cni-ztunnel-sock-dir
        - mountPath: /tmp
          name: tmp
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 30
      volumes:
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              path: istio-token
              expirationSeconds: 43200
              audience: istio-ca
      - name: istiod-ca-cert
        configMap:
          name: istio-ca-root-cert
      - name: cni-ztunnel-sock-dir
        hostPath:
          path: /var/run/ztunnel
          type: DirectoryOrCreate # ideally this would be a socket, but ztunnel may not have started yet.
      # pprof needs a writable /tmp, and we don't have that thanks to `readOnlyRootFilesystem: true`, so mount one
      - name: tmp
        emptyDir: {}
