#!/usr/bin/env bash
# Copyright Istio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Builds a local ztunnel docker image with the SPIFFE Broker provider
# compiled in, tagged with the name setup.sh expects.
#
# Self-contained: does not rely on a top-level Dockerfile or
# Makefile.docker target. Auto-detects host arch and writes a
# distroless-based Dockerfile under out/docker/.
#
# Knobs:
#   ZTUNNEL_IMAGE  — final tag (default: localhost/ztunnel:spiffe-broker-dev)
#   SKIP_BUILD=1   — reuse the existing out/rust/release/ztunnel binary
#                    (useful when iterating on the testbed itself)
#   BASE_IMAGE     — runtime base image
#                    (default: gcr.io/distroless/cc-debian12:nonroot)
#   TLS_MODE       — forwarded to scripts/release.sh (boring|aws-lc|openssl)

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../../.." && pwd)

: "${ZTUNNEL_IMAGE:=localhost/ztunnel:spiffe-broker-dev}"
: "${SKIP_BUILD:=0}"
# Use Debian 13 (trixie) distroless because the binary is built in this
# devcontainer on Ubuntu 24.04 (glibc 2.39) and links against GLIBC_2.38+.
# `cc-debian12` only ships glibc 2.36 which would crash at startup with:
#   /lib/.../libc.so.6: version `GLIBC_2.38' not found
: "${BASE_IMAGE:=gcr.io/distroless/cc-debian13:nonroot}"

log() {
  printf '\033[1;34m[build-ztunnel]\033[0m %s\n' "$*" >&2
}

detect_arch() {
  case "$(uname -m)" in
    x86_64)  echo amd64 ;;
    aarch64) echo arm64 ;;
    arm64)   echo arm64 ;;
    *)       printf 'error: unsupported host arch %s\n' "$(uname -m)" >&2; exit 1 ;;
  esac
}

write_dockerfile() {
  cat >"$1" <<'DOCKERFILE'
# Auto-generated by hack/spire-test/scripts/build-ztunnel-image.sh
ARG BASE_IMAGE=gcr.io/distroless/cc-debian12:nonroot
FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.source="https://github.com/istio/ztunnel"
LABEL org.opencontainers.image.description="ztunnel (SPIFFE Broker dev build)"

WORKDIR /
ARG TARGETARCH=amd64
COPY ${TARGETARCH}/ztunnel /usr/local/bin/ztunnel
ENTRYPOINT ["/usr/local/bin/ztunnel"]
DOCKERFILE
}

main() {
  cd "${REPO_ROOT}"

  local arch
  arch=$(detect_arch)
  log "host arch: ${arch}"

  if [[ "${SKIP_BUILD}" != "1" ]]; then
    # NOTE: we deliberately call cargo directly. `make release` ALSO uploads
    # the binary to gs://istio-build/ztunnel via gsutil and fails outside CI
    # with "DEST must be explicitly set".
    local features=()
    case "${TLS_MODE:-}" in
      boring)  features=(--no-default-features -F tls-boring) ;;
      aws-lc)  features=(--no-default-features -F tls-aws-lc) ;;
      openssl) features=(--no-default-features -F tls-openssl) ;;
      "")      ;;  # use Cargo.toml default (tls-aws-lc)
      *) printf 'error: unsupported TLS_MODE=%s\n' "${TLS_MODE}" >&2; exit 1 ;;
    esac
    log "compiling release binary (cargo build --release ${features[*]:-})"
    cargo build --release "${features[@]}"
  else
    log "SKIP_BUILD=1, reusing existing out/rust/release/ztunnel"
    [[ -x out/rust/release/ztunnel ]] \
      || { printf 'error: out/rust/release/ztunnel missing; run without SKIP_BUILD=1\n' >&2; exit 1; }
  fi

  log "staging build context under out/docker/"
  local ctx="out/docker"
  # Wipe any stale per-arch dirs from previous runs on a different host.
  rm -rf "${ctx}"
  mkdir -p "${ctx}/${arch}"
  cp out/rust/release/ztunnel "${ctx}/${arch}/ztunnel"
  write_dockerfile "${ctx}/Dockerfile"

  log "packaging docker image as ${ZTUNNEL_IMAGE} (TARGETARCH=${arch})"
  docker build \
    --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
    --build-arg "TARGETARCH=${arch}" \
    -t "${ZTUNNEL_IMAGE}" \
    "${ctx}"

  log "done."
  log "next: ./hack/spire-test/scripts/setup.sh"
}

main "$@"
